sources:
  - Sources
templates:
  - Templates
output:
  Sources/generated
args:
  xanchors: [left, right, leading, trailing, centerX]
  yanchors: [top, bottom, centerY]
  dimanchors: [width, height]
  uikit_anchors: [NSLayoutXAxisAnchor, NSLayoutYAxisAnchor, NSLayoutDimension]
